Regenerate .travis.yml
This commit was performed automatically by a script.
https://github.com/RyanGlScott/travis-maintenance

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -79,20 +79,25 @@ install:
       cabal new-update head.hackage -v
     fi
   - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
-  - "printf 'packages: \".\"\\n' > cabal.project"
+  - "printf 'packages: \"./logical-foundations\" \"./verified-functional-algorithms\"\\n' > cabal.project"
   - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
-  - echo 'package software-foundations' >> cabal.project
+  - echo 'package logical-foundations' >> cabal.project
+  - "echo '  ghc-options: -Werror' >> cabal.project"
+  - echo 'package verified-functional-algorithms' >> cabal.project
   - "echo '  ghc-options: -Werror' >> cabal.project"
   - touch cabal.project.local
-  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- software-foundations | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- logical-foundations | grep -vw -- verified-functional-algorithms | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
   - cat cabal.project || true
   - cat cabal.project.local || true
-  - if [ -f "./configure.ac" ]; then
-      (cd "." && autoreconf -i);
+  - if [ -f "./logical-foundations/configure.ac" ]; then
+      (cd "./logical-foundations" && autoreconf -i);
+    fi
+  - if [ -f "./verified-functional-algorithms/configure.ac" ]; then
+      (cd "./verified-functional-algorithms" && autoreconf -i);
     fi
   - rm -f cabal.project.freeze
   - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
-  - rm -rf .ghc.environment.* "."/dist
+  - rm -rf .ghc.environment.* "./logical-foundations"/dist "./verified-functional-algorithms"/dist
   - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
 # Here starts the actual work to be performed for the package under test;
@@ -103,12 +108,14 @@ script:
   - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
   - cd ${DISTDIR} || false
   - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
-  - "printf 'packages: software-foundations-*/*.cabal\\n' > cabal.project"
+  - "printf 'packages: logical-foundations-*/*.cabal verified-functional-algorithms-*/*.cabal\\n' > cabal.project"
   - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
-  - echo 'package software-foundations' >> cabal.project
+  - echo 'package logical-foundations' >> cabal.project
+  - "echo '  ghc-options: -Werror' >> cabal.project"
+  - echo 'package verified-functional-algorithms' >> cabal.project
   - "echo '  ghc-options: -Werror' >> cabal.project"
   - touch cabal.project.local
-  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- software-foundations | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- logical-foundations | grep -vw -- verified-functional-algorithms | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
   - cat cabal.project || true
   - cat cabal.project.local || true
 
@@ -116,7 +123,8 @@ script:
   - cabal new-build -w ${HC} ${TEST} ${BENCH} all
 
   # cabal check
-  - (cd software-foundations-* && cabal check)
+  - (cd logical-foundations-* && cabal check)
+  - (cd verified-functional-algorithms-* && cabal check)
 
   # haddock
   - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
